version: "3.5"

services:

    #MySQL Service
    admin-page:
        image: mysql:5.7.22
        container_name: admin-page
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: admin-page
            MYSQL_ROOT_PASSWORD: 'root'
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql

#  minio:
#    image: minio/minio
#    volumes:
#      - ./docker/minio/data:/data
#    ports:
#      - "9000:9000"
#    environment:
#      MINIO_ACCESS_KEY: minio-development
#      MINIO_SECRET_KEY: minio-secret
#    command: server /data
