version: "3.5"

services:

    #MySQL Service
    admin-db:
        image: mysql:5.7.22
        container_name: admin-db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: admin-page
            MYSQL_ROOT_PASSWORD: 'root'
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
