version: "3.5"

services:

    #MySQL Service
    admin-db:
        image: mysql:5.7.22
        container_name: admin-db
        restart: unless-stopped
        tty: true
        ports:
            - "3308:3306"
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
        environment:
            MYSQL_DATABASE: admin-page
            MYSQL_ROOT_PASSWORD: 'root'
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
